import Head from "next/head";
import Link from "next/link";

export default function About(): JSX.Element {
  return (
    <>
      <Head>
        <title>About | Copter-store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>About page</h2>
        <Link href="/">Home</Link>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus nostrum est dolores numquam commodi ipsum, unde laboriosam reprehenderit nam necessitatibus quos! At voluptatum soluta voluptatem rem maxime consequatur quaerat repellat?</p>
      </main>
    </>
  );
}