import styles from './insects.module.css';

import { Footer } from "@/components/Footer";

import { Header } from "@/components/Header";
import Head from 'next/head';
import { Hero } from '@/components/Hero';
import { EIcons, Icon } from '@/ui/Icon';
import { Section } from '@/components/Section';
import { PartHidden } from '@/components/PartHidden';

export default function Insects() {
    return (
        <>
            <Head>
                <title>About | Copter-store</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>
                <Hero src='/img/bg-insect.jpg' title='Высокоэффективные Энтомофаги' desc='Внесение  энтофагов  при помощи БПЛА увеличивает эффективность защиты растений до 90%'>
                    <ul className={styles.container}>
                        <li className={styles.item}>
                            <Icon name={EIcons.soy} />
                            <p>до 90% сои</p>
                        </li>
                        <li className={styles.item}>
                            <Icon name={EIcons.beet} />
                            <p>до 85 % сахарной свеклы</p>
                        </li>
                        <li className={styles.item}>
                            <Icon name={EIcons.raps} />
                            <p>до 70 % рапса</p>
                        </li>
                        <li className={styles.item}>
                            <Icon name={EIcons.sunflower} />
                            <p>до 85 % подсолнуха</p>
                        </li>
                        <li className={styles.item}>
                            <Icon name={EIcons.corn} />
                            <p>до 80 % кукурузы</p>
                        </li>
                        <li className={styles.item}>
                            <Icon name={EIcons.fruits} />
                            <p>до 90 % овощных и плодовых культур</p>
                        </li>
                    </ul>
                </Hero>
                <Section title='Энтомофаги' subtitle='Об Услуге'>
                    <PartHidden>
                    Компания AGROSCOUT за&nbsp;время научной работы совместно с&nbsp;ведущими НИИ страны разработала высокоэффективный метод защиты посевов от&nbsp;вредителей с&nbsp;использованием энтомофагов. Самый современный технопарк в&nbsp;стране, позволяет нам точно и&nbsp;быстро вносить трихограмму, златоглазку и&nbsp;габробракон на&nbsp;любых посевных площадях, включая труднодоступные участки, без применения тяжелой техники.
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Alias autem porro quam vel magni obcaecati facere consectetur sunt et ut, aspernatur quisquam voluptatum sit quaerat. Hic dignissimos vero sed omnis!
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consectetur alias nihil, quam, vitae officiis error, deleniti saepe laboriosam praesentium a deserunt fugit eos culpa unde! Possimus quis perspiciatis aut ipsa?
                    </PartHidden>
                </Section>
                <Section title='Приемущества внесения энтомофагов' subtitle='Плюсы использования'>
                    
                </Section>
            </main>
            <Footer />
        </>
    );
}