import React, { ReactNode } from "react";
import { IconAdapter, IconArrow, IconBasket, IconBattery, IconBeet, IconBlueprint, IconBuilding, IconBuilding2, IconButterfly, IconCamera, IconCheck, IconCheckedWhite, IconCloseLine, IconCoding, IconCompany, IconContacts, IconCoords, IconCopter, IconCopter2, IconCopter3, IconCorn, IconDelivery, IconDrone, IconDrone2, IconDrone3, IconDrone4, IconDrone5, IconEqualizer, IconFly, IconForest, IconFruits, IconFuel, IconGenerator, IconGeolocation, IconHarvest, IconHome, IconInsect, IconInsect2, IconInstagram, IconLan, IconMap, IconMapGeo, IconMenu, IconModules, IconMotorcycle, IconMountain, IconMulcamera, IconNews, IconPeople, IconPhone, IconPower, IconRaps, IconResolution, IconRub, IconScale, IconSecurity, IconServices, IconSetting, IconSettingDrone, IconSoy, IconSpray, IconSunFlower, IconTech, IconTelegram, IconTermometr, IconThermal, IconTikTok, IconTime, IconTools, IconTractor, IconTree, IconVk, IconWallet, IconWeb, IconWechat, IconWhatsUp, IconWidth } from "../Icons";



// type TIconSizes = 20 | 16 | 14 | 12 | 10;

interface IIconProps {
  name: EIcons;
}

export enum EIcons {
  people = 'people',
  tech = 'tech',
  vk = 'vk',
  instagram = 'instagram',
  tiktok = 'tiktok',
  home = 'home',
  phone = 'phone',
  basket = 'basket',
  menu = 'menu',
  insect = 'insect',
  drone = 'drone',
  map = 'map',
  copter = 'copter',
  news = 'news',
  company = 'company',
  contacts = 'contacts',
  whatsup = 'whatsup',
  telegram = 'telegram',
  wechat = 'wechat',
  rub = 'rub',
  services = 'services',
  copter2 = 'copter2',
  web = 'web',
  arrow = 'arrow',
  soy = 'soy',
  beet = 'beet',
  raps = 'raps',
  sunflower = 'sunflower',
  corn = 'corn',
  fruits = 'fruits',
  wallet = 'wallet',
  copter3 = 'copter3',
  insect2 = 'insect2',
  drone2 = 'drone2',
  butterfly = 'butterfly',
  time = 'time',
  spray = 'spray',
  tractor = 'tractor',
  fly = 'fly',
  closeline = 'closeline',
  check = 'check',
  setting = 'setting',
  tools = 'tools',
  resolution = 'resolution',
  coords = 'coords',
  checkwhite = 'checkwhite',
  scale = 'scale',
  harvest = 'harvest',
  forest = 'forest',
  blueprint = 'blueprint',
  power = 'power',
  building = 'building',
  building2 = 'building2',
  mountain = 'mountain',
  termometr = 'termometr',
  width = 'width',
  fuel = 'fuel',
  drone3 = 'drone3',
  drone4 = 'drone4',
  drone5 = 'drone5',
  motorcycle = 'motorcycle',
  camera = 'camera',
  mulcamera = 'mulcamera',
  thermal = 'thermal',
  modules = 'modules',
  adapter = 'adapter',
  battery = 'battery',
  lan = 'lan',
  generator = 'generator',
  equalizer = 'equalizer',
  mapgeo = 'mapgeo',
  settingDrone = 'settingDrone',
  coding = 'coding',
  tree = 'tree',
  delivery = 'delivery',
  security = 'security',
  geolocation = 'geolocation',
}

const icons: Record<EIcons, ReactNode> = {
  [EIcons.people]: <IconPeople />,
  [EIcons.tech]: <IconTech />,
  [EIcons.vk]: <IconVk />,
  [EIcons.instagram]: <IconInstagram />,
  [EIcons.tiktok]: <IconTikTok />,
  [EIcons.home]: <IconHome />,
  [EIcons.phone]: <IconPhone />,
  [EIcons.basket]: <IconBasket />,
  [EIcons.menu]: <IconMenu />,
  [EIcons.insect]: <IconInsect />,
  [EIcons.drone]: <IconDrone />,
  [EIcons.map]: <IconMap />,
  [EIcons.copter]: <IconCopter />,
  [EIcons.news]: <IconNews />,
  [EIcons.company]: <IconCompany />,
  [EIcons.contacts]: <IconContacts />,
  [EIcons.whatsup]: <IconWhatsUp />,
  [EIcons.telegram]: <IconTelegram />,
  [EIcons.wechat]: <IconWechat />,
  [EIcons.rub]: <IconRub />,
  [EIcons.services]: <IconServices />,
  [EIcons.copter2]: <IconCopter2 />,
  [EIcons.web]: <IconWeb />,
  [EIcons.arrow]: <IconArrow />,
  [EIcons.soy]: <IconSoy />,
  [EIcons.beet]: <IconBeet />,
  [EIcons.raps]: <IconRaps />,
  [EIcons.sunflower]: <IconSunFlower />,
  [EIcons.corn]: <IconCorn />,
  [EIcons.fruits]: <IconFruits />,
  [EIcons.wallet]: <IconWallet />,
  [EIcons.copter3]: <IconCopter3 />,
  [EIcons.insect2]: <IconInsect2 />,
  [EIcons.drone2]: <IconDrone2 />,
  [EIcons.butterfly]: <IconButterfly />,
  [EIcons.time]: <IconTime />,
  [EIcons.spray]: <IconSpray />,
  [EIcons.tractor]: <IconTractor />,
  [EIcons.fly]: <IconFly />,
  [EIcons.closeline]: <IconCloseLine />,
  [EIcons.check]: <IconCheck />,
  [EIcons.setting]: <IconSetting />,
  [EIcons.tools]: <IconTools />,
  [EIcons.resolution]: <IconResolution />,
  [EIcons.coords]: <IconCoords />,
  [EIcons.checkwhite]: <IconCheckedWhite />,
  [EIcons.scale]: <IconScale />,
  [EIcons.harvest]: <IconHarvest />,
  [EIcons.forest]: <IconForest />,
  [EIcons.blueprint]: <IconBlueprint />,
  [EIcons.power]: <IconPower />,
  [EIcons.building]: <IconBuilding />,
  [EIcons.building2]: <IconBuilding2 />,
  [EIcons.mountain]: <IconMountain />,
  [EIcons.termometr]: <IconTermometr />,
  [EIcons.width]: <IconWidth />,
  [EIcons.fuel]: <IconFuel />,
  [EIcons.drone3]: <IconDrone3 />,
  [EIcons.drone4]: <IconDrone4 />,
  [EIcons.drone5]: <IconDrone5 />,
  [EIcons.motorcycle]: <IconMotorcycle />,
  [EIcons.camera]: <IconCamera />,
  [EIcons.mulcamera]: <IconMulcamera />,
  [EIcons.thermal]: <IconThermal />,
  [EIcons.modules]: <IconModules />,
  [EIcons.adapter]: <IconAdapter />,
  [EIcons.battery]: <IconBattery />,
  [EIcons.lan]: <IconLan />,
  [EIcons.generator]: <IconGenerator />,
  [EIcons.equalizer]: <IconEqualizer />,
  [EIcons.mapgeo]: <IconMapGeo />,
  [EIcons.settingDrone]: <IconSettingDrone />,
  [EIcons.coding]: <IconCoding />,
  [EIcons.tree]: <IconTree />,
  [EIcons.delivery]: <IconDelivery />,
  [EIcons.security]: <IconSecurity />,
  [EIcons.geolocation]: <IconGeolocation/>
};


export function Icon({ name }: IIconProps): JSX.Element | null {

  if (typeof name === 'undefined') return null;

  return (
    <>
      {icons[name]}
    </>
  );
}
