import { Header } from '@/components/Header';
import { Hero } from '@/components/Hero';
import styles from '@/styles/Home.module.css';

import Head from '../../node_modules/next/head';

import { Roboto } from 'next/font/google';
import { Section } from '@/components/Section';
import { EIcons, Icon } from '@/ui/Icon';

const roboto = Roboto({
  subsets: ['cyrillic', 'latin'], display: 'swap',
  weight: ['400', '700']
});


export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Home | Copter-store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${roboto.className}`}>
        <Header />
        <Hero src={'/img/copter-bg-1.jpg'}>
          <>
            <h1 className={styles.h1}>AgroScout - беспилотные технологии для сельского хозяйства и промышлености</h1>
            <div className={styles['info-wrap']}>
              <div className={styles.info}>
                <span className={styles['span-info']}>50 000 Га</span>
                <br/>
                ежегодной обработки
              </div>
              <div className={styles.info}>
                <span className={styles['span-info']}>30% </span>
                <br/>
                экономии средств
              </div>
              <div className={styles.info}>
                <span className={styles['span-info']}>10 команд</span>
                <br/>
                экономии средств
              </div>
            </div>
          </>
        </Hero>
        <Section title='Наши преимущества' subtitle='почему нам доверяют'>
          <div>
            <Icon name={EIcons.vk}/>
            <Icon name={EIcons.instagram}/>
            <Icon name={EIcons.tiktok}/>
            <Icon name={EIcons.basket}/>
            <Icon name={EIcons.menu}/>
            <Icon name={EIcons.home}/>
            <Icon name={EIcons.insect}/>
            <Icon name={EIcons.drone}/>
            <Icon name={EIcons.map}/>
            <Icon name={EIcons.copter}/>
            <Icon name={EIcons.news}/>
            <Icon name={EIcons.company}/>
            <Icon name={EIcons.contacts}/>
            <Icon name={EIcons.whatsup}/>
            <Icon name={EIcons.telegram}/>
            <Icon name={EIcons.wechat}/>
            <Icon name={EIcons.people}/>
            <Icon name={EIcons.tech}/>
            <Icon name={EIcons.rub}/>
            <Icon name={EIcons.services}/>
            <Icon name={EIcons.copter2}/>
            <Icon name={EIcons.web}/>
            <Icon name={EIcons.arrow}/>
            <Icon name={EIcons.soy}/>
            <Icon name={EIcons.beet}/>
            <Icon name={EIcons.raps}/>
            <Icon name={EIcons.sunflower}/>
            <Icon name={EIcons.corn}/>
            <Icon name={EIcons.fruits}/>
            <Icon name={EIcons.wallet}/>
            <Icon name={EIcons.copter3}/>
            <Icon name={EIcons.drone2}/>
            <Icon name={EIcons.butterfly}/>
            <Icon name={EIcons.time}/>
            <Icon name={EIcons.spray}/>
            <Icon name={EIcons.tractor}/>
            <Icon name={EIcons.fly}/>
            <Icon name={EIcons.closeline}/>
            <Icon name={EIcons.check}/>
            <Icon name={EIcons.setting}/>
            <Icon name={EIcons.tools}/>
            <Icon name={EIcons.resolution}/>
            <Icon name={EIcons.coords}/>
            <Icon name={EIcons.checkwhite}/>
            <Icon name={EIcons.scale}/>
            <Icon name={EIcons.harvest}/>
            <Icon name={EIcons.forest}/>
            <Icon name={EIcons.blueprint}/>
            <Icon name={EIcons.power}/>
            <Icon name={EIcons.building}/>
            <Icon name={EIcons.building2}/>
            <Icon name={EIcons.mountain}/>
            <Icon name={EIcons.termometr}/>
            <Icon name={EIcons.width}/>
            <Icon name={EIcons.fuel}/>
            <Icon name={EIcons.drone3}/>
            <Icon name={EIcons.drone4}/>
            <Icon name={EIcons.drone5}/>
            <Icon name={EIcons.motorcycle}/>
            <Icon name={EIcons.camera}/>
            <Icon name={EIcons.mulcamera}/>
            <Icon name={EIcons.thermal}/>
            <Icon name={EIcons.modules}/>
            <Icon name={EIcons.adapter}/>
            <Icon name={EIcons.battery}/>
            <Icon name={EIcons.lan}/>
            <Icon name={EIcons.generator}/>
            <Icon name={EIcons.equalizer}/>
            <Icon name={EIcons.mapgeo}/>
            <Icon name={EIcons.settingDrone}/>
            <Icon name={EIcons.coding}/>
            <Icon name={EIcons.tree}/>
            <Icon name={EIcons.delivery}/>
            <Icon name={EIcons.security}/>
            <Icon name={EIcons.geolocation}/>
          </div>
        </Section>
      </main>
    </>
  );
}
