import { Header } from '@/components/Header';
import { Hero } from '@/components/Hero';
import styles from '@/styles/Home.module.css';

import Head from '../../node_modules/next/head';

import { Roboto } from 'next/font/google';
import { Section } from '@/components/Section';

import { VitrinaSVG } from '@/components/VitrinaSVG';
import { CardInfo } from '@/components/CardInfo';
import { EIcons } from '@/ui/Icon';

const roboto = Roboto({
  subsets: ['cyrillic', 'latin'], display: 'swap',
  weight: ['300', '400', '700']
});


export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Home | Copter-store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${roboto.className}`}>
        <Header />
        <Hero src={'/img/copter-bg-1.jpg'}>
          <>
            <h1 className={styles.h1}>AgroScout - беспилотные технологии для сельского хозяйства и промышлености</h1>
            <div className={styles['info-wrap']}>
              <div className={styles.info}>
                <span className={styles['span-info']}>50 000 Га</span>
                <br />
                ежегодной обработки
              </div>
              <div className={styles.info}>
                <span className={styles['span-info']}>30% </span>
                <br />
                экономии средств
              </div>
              <div className={styles.info}>
                <span className={styles['span-info']}>10 команд</span>
                <br />
                экономии средств
              </div>
            </div>
          </>
        </Hero>
        <Section title='Наши преимущества' subtitle='почему нам доверяют'>
          <div className={styles['card-info-wrap']}>
            <CardInfo icon={EIcons.people} title='Квалифицированные сотрудники'>
              Все наши сотрудники имеют многолетний опыт работы в&nbsp;сфере беспилотной авиации. Нами было реализовано множество проектов различной тематики и&nbsp;самой различной сложности.
            </CardInfo>
            <CardInfo icon={EIcons.tech} title='Высокотехнологичное оборудование '>
              Наша компания использует современное оборудование, которое обеспечивает высокое качество в&nbsp;выполнении поставленных задач.
            </CardInfo>
            <CardInfo icon={EIcons.rub} title='Экономия'>
              Использование беспилотных технологий экономит вам много времени и&nbsp;денег. За&nbsp;счет отсутствия технологической колеи сохраняется до&nbsp;6% урожая. Снижение расхода препаратов до&nbsp;30%
            </CardInfo>
            <CardInfo icon={EIcons.services} title='Оперативность'>
              За&nbsp;рабочую смену наши специалисты способны защитить более 1000 гектар ваших полей, кустарников и&nbsp;деревьев.
            </CardInfo>
            <CardInfo icon={EIcons.drone} title='Собственное производство'>
              Мы&nbsp;разрабатываем и&nbsp;производим беспилотные летательные аппараты, поэтому знаем все тонкости их&nbsp;работы и&nbsp;можем настроить их&nbsp;под конкретные задачи и&nbsp;потребности клиентов.
            </CardInfo>
            <CardInfo icon={EIcons.web} title='Свой сервис'>
              Любой наш аппарат можно сдать на&nbsp;плановое техническое обслуживание или&nbsp;же в&nbsp;ремонт в&nbsp;наш собственный сервис,
              который гарантирует качество и&nbsp;оперативность выполнения работ.
            </CardInfo>
          </div>
        </Section>
        <VitrinaSVG />
      </main>
    </>
  );
}
